### ISSUE TITLE
Can't find CSS file

### ISSUE THREAD

**Issue by NickToye** [pattern-lab/plugin-node-tab#10]
I am on 2.6.0-alpha
Gulp CLI 1.2.2
Gulp Local 4.0.0-alpha.2

I've a very basic fresh install of Pattern Lab, I have a folder in the _patterns folder called Nucelus, and this has 2 files.  

basic.mustache
basic.css

The mustache file shows up in the tab, but the css tab shows this error:

Cannot GET /patterns/nucleus-basic/nucleus-basic.css?1475409729027

If there is any other information I can get to you I will, just let me know.  I'm kind of new to this kind of stuff.

**Comment by ioss** [comment]
Have you added 
...  
    **"plugin-node-tab": false**
}

to the end of your patternlab-config.json?

**Comment by NickToye** [comment]
Was I supposed to?

**Comment by NickToye** [comment]
ok, that works.  Now this throws up another issue for me, how come setting it to false enables the plugin?

**Comment by ioss** [comment]
As far as I have read the code:
Read it as:  Is there a plugin and has it been initialized.
So the key (`plugin-node-tab`) makes it find the plugin at all & the plugin itself checks if the value is `false`, if so, it does its initialization and sets the value (runtime only) to `true`.

I agree, it is confusing. Better would have been:
If it is `false`skip the plugin, otherwise (if it's `true`or some config) run it.
The plugin should have used another way to check, if it was initialized.

(I am just writing a plugin, I'll take that into consideration for mine)

**Comment by NickToye** [comment]
Kind of makes sense. :)
